### ISSUE TITLE
更新了英语语言之后生成博客时发生错误

### ISSUE THREAD

**Issue by Steven1677** [gaoryrt/hexo-theme-pln#10]
错误相关信息如下：
ERROR Process failed: languages/en.yml

**Comment by aloisdg** [comment]
I think you have the same error than me ( #11 ).  I shared a quick fix.

Also, could you post a copy of your issue in english? Thank you 😄

**Comment by Steven1677** [comment]
@aloisdg Sorry for using Chinese. You are right, using English can help more people.

**Comment by aloisdg** [comment]
@Stephen-Chen No problem. Thank you very much :)

Did you try my fix?

**Comment by Steven1677** [comment]
@aloisdg It just works.
Thank you.

**Comment by aloisdg** [comment]
You are welcome!

**Comment by Steven1677** [comment]
see #11

**Comment by gaoryrt** [comment]
thank you guys !
