### ISSUE TITLE
配置的几个问题

### ISSUE THREAD

**Issue by ghost** [gaoryrt/hexo-theme-pln#14]
1. 怎样将引用的段落的默认的斜体改成正体？因为写代码或者 mathjax 数学公式的时候如果用斜体的话不好看。
2. 怎样屏蔽侧边栏显示的版权信息？

**Comment by gaoryrt** [comment]
对于这两个要求，可能需要你自行修改主题的css文件，具体的css文件位置在`hexo/theme/pln/source/css/m.min.css`，需要你用文件编辑器打开这个`m.min.css`文件，在该文件最后加上下面两行：

```
blockquote { font-style: normal; }
.right-foot { display: none; }
```

第一行将应用部分的斜体改为了正常。

第二行设置了版权信息不显示。

修改后重新`hexo g`生成博客，发布就行了。

希望能帮助到你。
