### ISSUE TITLE
关于目录分类归类问题

### ISSUE THREAD

**Issue by fredchenjialin** [gaoryrt/hexo-theme-pln#15]
我的文章开头结构如下：

> title: pintos学习笔记0
> date: 2015-09-13 10:14:48
> categories:
>  - Diary
> tags:
>  - pintos

我的问题是，我的目录页面显示不完全，而且，出现目录重复。
![image](https://cloud.githubusercontent.com/assets/5558295/19186887/fb4d8ef8-8cba-11e6-95b8-4b3098796a0f.png)

**Comment by gaoryrt** [comment]
我是这样设置的：

```
title: Hello World
date: 2015-09-08 01:25:00
categories: 疑似机器人
tags: [try, cool]
---
```

注意这里`categories`只能有一个值，如果想设置多个的话，应该使用`tags`。
还有重复的问题，我这里看不到效果，只能靠猜。是不是大小写或者空格导致的不同？

**Comment by gaoryrt** [comment]
还有，那个列表中只会显示`categories` 
并不会在展开的菜单中显示`tags`
如果想看`tags`的话，只能从某个文章里面的标签链接进入

**Comment by aloisdg** [comment]
Can you translate it in english too?

**Comment by fredchenjialin** [comment]
> title: pintos学习笔记1
> date: 2015-09-16 14:42:09
> categories:
>  - pintos

我的设置如上，我所说的显示不完全的意思是，像这个页面，http://fredchenjialin.github.io/categories/Diary/ ，尽然分页了。。现在这个页面下面的导航是我自己加的，因为我直接使用您的主题没有办法达到“主页面是分页的，分类页面下是不分页的”的效果，我不知道你那里是怎么做的？我在根目录下的_config.yml中分页的设置是默认的

```
# Pagination
## Set per_page to 0 to disable pagination
#per_page: 4
#pagination_dir: page
```

**Comment by aloisdg** [comment]
Ok nevermind I will let you guys handle it. Just poke me if I need to do something. :)

**Comment by fredchenjialin** [comment]
我的哥，我的问题解决了，原来都是在_config.yml里面设置，我好傻逼，谢谢。

And hello aloisdg, I have poor English, sorry. BUT,THANK YOU ALL!!!

**Comment by aloisdg** [comment]
No problem. 
没问题。

**Comment by gaoryrt** [comment]
@aloisdg i have a poor English too.
In short, @fredchenjialin found his tag page be paged(every tag page only have 4 article items as he mentioned in the later comment), and he got two same tag-link in the index page.
So I suggested him to check if he wrote the markdown correctly.
In the end, he found he wrote the `_config.yml` wrong, and fixed it by himself.
¯\_(ツ)_/¯

**Comment by aloisdg** [comment]
Good for him 👍
