### ISSUE TITLE
标签栏能显示的太少，而且无法滚动，多了之后看不全。The dropdown-content can not be scrolled when there are too many tabs.

### ISSUE THREAD

**Issue by marshalys** [gaoryrt/hexo-theme-pln#16]
能否优化一下，谢谢！

**Comment by gaoryrt** [comment]
The dropdown-content can not be scrolled when there are too many tabs bug fixed.
Try `git pull` then `hexo clean` and `hexo d -g`

**Comment by gaoryrt** [comment]
wow.
so good.
fixed.

**Comment by marshalys** [comment]
thank you!
