### ISSUE TITLE
左上角无法显示logo和图标

### ISSUE THREAD

**Issue by seahuai** [gaoryrt/hexo-theme-pln#19]
搜索栏左边的内容显示不出来

**Comment by JayceLau** [comment]
给某篇post添加categories就会显示出来了

**Comment by gaoryrt** [comment]
@seahuai 随手关issue啊～

**Comment by shuiRong** [comment]
发现个小问题：没有任何文章添加categories的时候，不仅分类，Logo的文字也没有显示。添加了之后，正常.

**Comment by gaoryrt** [comment]
Fixed in https://github.com/gaoryrt/hexo-theme-pln/pull/38
Thanks @shuiRong

**Comment by shuiRong** [comment]
哈哈哈哈，17年的issue。(还发现我18年评论过2333)

**Comment by gaoryrt** [comment]
《论懒惰》
