### ISSUE TITLE
关于TOC的问题

### ISSUE THREAD

**Issue by JayceLau** [gaoryrt/hexo-theme-pln#20]
是否支持固定TOC？post过长时，TOC的需求十分迫切

**Comment by pingeek007** [comment]
同意！好像确实没看见TOC

**Comment by gaoryrt** [comment]
暂时没有支持目录的想法。。。
@JayceLau  @pingeek007

**Comment by navono** [comment]
@gaoryrt 有思路吗？说说思路，我看下我能不能搞出来。

**Comment by navono** [comment]
找到一个比较挫的方法，在article.ejs中加入
```js
<%- toc(page.content) %>
```
唯一的问题就是，这个toc是显示在文章顶部，往下拉的时候就不见了。最好的效果是显示在左侧。

要显示在左侧就需要跟右侧显示的那个一样，需要写css，这个还不是太懂。

**Comment by gaoryrt** [comment]
@navono 问题就是不晓得目录放在哪里比较好看。。。

**Comment by navono** [comment]
@gaoryrt 左侧嘛。放左侧需要和关闭按钮重新设计一下。如果硬塞进去会和关闭按钮有点格格不入。

**Comment by navono** [comment]
或者在关闭按钮下面再弄个nav按钮，点击从左侧动态弹出显示toc。可以浮动。

**Comment by pwxcoo** [comment]
同，希望开发者有空能一个toc模块，不是固定也ok

**Comment by gaoryrt** [comment]
![image](https://user-images.githubusercontent.com/5306513/35765407-f47ba9c8-08fd-11e8-8228-21690c658b6c.png)

**Comment by gaoryrt** [comment]
做了个临时版的，有问题的话就新开 issue 吧

[首页有如何更新](https://github.com/gaoryrt/hexo-theme-pln#update)

@JayceLau @pingeek007 @navono @pwxcoo @willmasters
