### ISSUE TITLE
代码片段会对不齐

### ISSUE THREAD

**Issue by agrass-GitHub** [gaoryrt/hexo-theme-pln#24]
这里分别是两段代码的演示，请问是什么原因导致？
![image](https://user-images.githubusercontent.com/30621542/29107545-48fde510-7d0d-11e7-89d0-5eb42ac1a6e8.png)
![image](https://user-images.githubusercontent.com/30621542/29107553-4f16d8d0-7d0d-11e7-9628-65c0c56f2639.png)

**Comment by gaoryrt** [comment]
能给下md或者是生成的html来看一下？

**Comment by agrass-GitHub** [comment]
---
title:  TreeJson
date: 2017-08-09 14:06:35
tags: JS
categories: 技术发展
---

把扁平化的数据转为成树形结构的Json数据。


### API

jsonTree(data, config)

* data: 数组,扁平化数据
* config: 配置对象
    - id 数据里的id string类型
    - pid 数据里的父id string类型
    - children 生成结果中子节点的字段名 string类型
* 返回一个树形结构的对象


```js
console.log(result)
console.log(JSON.stringify(result, null, '\t'));
console.log(result)
console.log(JSON.stringify(result, null, '\t'));
console.log(result)
console.log(JSON.stringify(result, null, '\t'));
console.log(result)
console.log(JSON.stringify(result, null, '\t'));
console.log(result)
console.log(JSON.stringify(result, null, '\t'));
console.log(result)
console.log(JSON.stringify(result, null, '\t'));
console.log(result)
console.log(JSON.stringify(result, null, '\t'));
```
<br>

```js
var jsonTree = function (data,config) {
  var id = config.id || 'id',
      pid = config.pid || 'pid',
      children = config.children || 'children';

  var idMap = [],
      jsonTree = [];

  data.forEach(function(v){
    idMap[v[id]] = v;
  });

  data.forEach(function(v){
    var parent = idMap[v[pid]];
    if(parent) {
      !parent[children] && (parent[children] = []);
      parent[children].push(v);
    } else {
      jsonTree.push(v);
    }
  });
  return jsonTree;
};
```

**Comment by agrass-GitHub** [comment]
这样是否可以？

**Comment by agrass-GitHub** [comment]
如果你找到问题所在，请告诉我谢谢。(๑•̀ㅂ•́)و✧

**Comment by gaoryrt** [comment]
这个问题出现在空行上，把第二段的代码里面的空行都去掉就可以了吧

**Comment by gaoryrt** [comment]
但是修复要等我上新，等下班回家搞

**Comment by gaoryrt** [comment]
我自己搞出来是有空行／没有问题的，试试更新到最新的hexo？

**Comment by agrass-GitHub** [comment]
问题的确出现在空行上，删了就可以，不删布局就有问题。hexo 已经是最新。很郁闷。

**Comment by agrass-GitHub** [comment]
你好，我发现空行上的.line 是没有高度的，我在css强制设置为.line{30px},pc显示正常，手机显示不正常，手机端测试大概高度为18px，请问有什么更好的解决方法吗

**Comment by gaoryrt** [comment]
看到你的博客已经解决了这个问题，可否愿意 fork 一份 push 来？
