### ISSUE TITLE
conflict with .back button & side navigation bar

### ISSUE THREAD

**Issue by wonyoungseo** [gaoryrt/hexo-theme-pln#27]
Hi :)

When I have a long & full side navigation bar due to many contents inside the post, I am not able to click the back (X) button.

If the I have short nagivation bar, I can click the back button to go to the root directory.

How can I fix this?

Thanks in advance

**Comment by gaoryrt** [comment]
for a quick fix, just add follow lines in your `m.min.css` file:
```css
.back {z-index:2}
```

**Comment by wonyoungseo** [comment]
Thanks for the swift feedback ! the solution helps for now :)

I have one more question, 
have you managed to activate the search function?
I don't know if I've missed in on `_config.yml` but I couldn't activate the search function and neither is your demo page. Insight search function would be really great for example.

If you have updated the function, I would appreciate if you can share it :)

my page is <http://lucaseo.github.io>


Thank you !!!!
