### ISSUE TITLE
TOC bug?

### ISSUE THREAD

**Issue by JayceLau** [gaoryrt/hexo-theme-pln#28]
今天更新后，发现一个问题如下，TOC丢失了第一个字
![image](https://user-images.githubusercontent.com/16794535/39659267-41aae524-5057-11e8-8d85-59cd7c362b4b.png)
是否跟中文有关？

**Comment by gaoryrt** [comment]
可以右键 inspect 看一下 element 里面 html 的内容是不是正常的先

**Comment by JayceLau** [comment]
no
![image](https://user-images.githubusercontent.com/16794535/39660247-500f5972-506d-11e8-96de-66f252ab6018.png)

**Comment by gaoryrt** [comment]
找了个 [你的博客页](https://jaycelau.github.io/2017/07/04/Oracle-Linux%E4%B8%8B%E5%AE%89%E8%A3%85ASMLIB/)，貌似是 hexo 提供的 toc 少了？
我使用 hexo-theme-unit-test 没有发现问题：
![image](https://user-images.githubusercontent.com/5306513/39660286-18424cd8-506e-11e8-8b59-a2e21909966e.png)

**Comment by JayceLau** [comment]
所以要去[hexo](https://github.com/hexojs/hexo)下提issue吗😂

**Comment by gaoryrt** [comment]
建议先试试 hexo clean 
然后再试试升级相关的包：
![image](https://user-images.githubusercontent.com/5306513/39660753-e1d50578-5077-11e8-8a0f-3844c7dcaf7b.png)
如果还不行可能只有去 hexo 那边开 issue 了

**Comment by JayceLau** [comment]
OK，更新hexo后，恢复正常。
