### ISSUE TITLE
不支持有序列表吗？

### ISSUE THREAD

**Issue by JayceLau** [gaoryrt/hexo-theme-pln#30]
有序列表渲染后跟无序列表样式完全一样
![image](https://user-images.githubusercontent.com/16794535/44711295-9a203b80-aae0-11e8-8271-bbc53c3744c4.png)
Typora中样式⬆️
![image](https://user-images.githubusercontent.com/16794535/44711317-aad0b180-aae0-11e8-98dc-ea9afb3d3b81.png)
渲染后的样式⬆️

**Comment by gaoryrt** [comment]
是的，就是这个样式。
所以需要么。。。

**Comment by JayceLau** [comment]
还是需要的吧😂
不然不是丢了有序列表的这个feature不是🤝

**Comment by gaoryrt** [comment]
fixed on https://github.com/gaoryrt/hexo-theme-pln/commit/523f35179225ad433e51d9a7db3623514cedcede

**Comment by JayceLau** [comment]
赞👍
