### ISSUE TITLE
UV/PV统计是否出现了异常？

### ISSUE THREAD

**Issue by JayceLau** [gaoryrt/hexo-theme-pln#31]
今天发现UV/PV显示异常，去你的网站看了一下，发现也一样，是否出现了异常？
![image](https://user-images.githubusercontent.com/16794535/49008865-e8111200-f1a9-11e8-94d8-d5684e97a361.png)

**Comment by gaoryrt** [comment]
以前使用 [busuanzi](https://busuanzi.ibruce.info/) 作为统计，但是上个月七牛回收域名，老版本的不蒜子就失效了。
已经在 https://github.com/gaoryrt/hexo-theme-pln/commit/1d7e9d31185c762ccdd6ceb0c3f2b96790d0f868 修复了这个问题
参照 [README#update](https://github.com/gaoryrt/hexo-theme-pln#update) 进行更新就好了

**Comment by JayceLau** [comment]
OK，已更新，感谢耐心说明！
