### ISSUE TITLE
无序列表显示问题

### ISSUE THREAD

**Issue by snowden-fu** [gaoryrt/hexo-theme-pln#36]
<img width="513" alt="Screen Shot 2019-08-13 at 11 55 35" src="https://user-images.githubusercontent.com/24203166/62914092-42e2ac00-bdc1-11e9-9fe4-6d89b0520199.png">
无序列表显示不正常

**Comment by shuiRong** [comment]
我也遇到过，忘了什么情况出现了。貌似作者也没多少空。可以的话，你提个PR？

**Comment by snowden-fu** [comment]
我也不清楚什么情况了，今天刚刚测试结果没什么问题。
<img width="359" alt="Screen Shot 2020-01-04 at 09 59 49" src="https://user-images.githubusercontent.com/24203166/71758315-f5361f80-2ed8-11ea-8ddf-2d29181b8123.png">

**Comment by gaoryrt** [comment]
fixed in https://github.com/gaoryrt/hexo-theme-pln/commit/ebb7475f5999ef8aa5ad838989c8216c964bef8c

貌似 ol > li 里面不是 textcontent，而是 p，p 标签不是行内元素所以自动换行了
之前没出现是因为之前都是 textcontent
其他主题不会出现是因为他们没有用 `:before {content: '·'}` 重写 li 的 list-style
是的，默认无需列表的那个点太丑了
