### ISSUE TITLE
资源引用方式应该使用相对路径｜解决博客放到子目录的问题

### ISSUE THREAD

**Issue by shuiRong** [gaoryrt/hexo-theme-pln#37]
> 国际惯例，先赞美作者提供这样简约漂亮的主题。

因为要把[博客](https://linshuirong.cn/blog/)放到域名子目录下，下午折腾了下，最后解决了。但遇到了些坑，在这里提出来，方便后人根据搜索引擎过来。
1. 如果什么都不做，直接把博客扔到子目录下，博客css js 等资源引用错误。
2. 发现hexo文档中有提到子目录，说需要在总配置里配置`url` `root`项，试过，无效。（我还得以为配置过后，hexo会自动把主题里的资源引用改成正确的，即考虑到子目录。）
3. 最后我的解决方式是，1. 在`head.ejs`中增加`<base href="/blog/" />`，同时修改各文件中引用文件为相对路径。 

需要我提个PR的话，大声喊我。

**Comment by gaoryrt** [comment]
当然是欢迎的（其实是太懒了

**Comment by shuiRong** [comment]
好，过几天有空了提

**Comment by zhangyige8848** [comment]
要加项目路径，太不优雅了
