### ISSUE TITLE
是否有“关于我”页面和“友情链接”页面的模板？及关于“上一篇”“下一篇”的建议

### ISSUE THREAD

**Issue by Steven1677** [gaoryrt/hexo-theme-pln#6]
看了您的博客，发现这两方面做得不错，但是在主题文件中并没有发现相关的模板以供使用，是否有把这两个模板公开的打算？

**Comment by gaoryrt** [comment]
抱歉回复的时间这么晚，实在是没有看到通知。
您说的关于我和友情链接页面，我都是手动将数据添加进html文件的，所以并没有您想要的「模板」。
若是想要的话我可以尝试用vue将模板和数据分离开，但是数据需要填写在类似json的js中。。。
我还要想想还有没有简单一点的办法

**Comment by gaoryrt** [comment]
https://github.com/gaoryrt/extensions-for-theme-Pln  
新添了一个项目，可以暂时看一看~

**Comment by Steven1677** [comment]
谢谢回复！您的这种设计的确不错。如果能够把这两个页面的设计和博客本身的设计统一风格，会不会更好一些？

**Comment by Steven1677** [comment]
再提一个建议，能否在文章的结尾处加上“上一篇”和“下一篇”的按钮？

**Comment by gaoryrt** [comment]
@Stephen-Chen 「关于我」是个人简历页面，基本上是不可能跟这个主题统一的，友链我自己也没想好怎么好看。。。

**Comment by Steven1677** [comment]
@gaoryrt 看到新加入了search的功能，是否能说明一下依赖什么插件？

**Comment by gaoryrt** [comment]
@Stephen-Chen http://hahack.com/codes/local-search-engine-for-hexo/

**Comment by Steven1677** [comment]
@gaoryrt 是只要在根目录配置就好了吗？本主题的文件要进行配置吗？

**Comment by gaoryrt** [comment]
@Stephen-Chen 本项目七月五日更新的版本中已经有了搜索功能的模板，使用上面链接中提到的[hexo-generator-search](https://github.com/PaicHyperionDev/hexo-generator-search)插件，没有问题的话，pull之后，安装hexo-generator-search插件，然后hexo g应该就可以用了。要是不行的话可能还要看看 [插件原作者的文章](http://hahack.com/codes/local-search-engine-for-hexo/)。
