### ISSUE TITLE
请问如何添加网页图标？

### ISSUE THREAD

**Issue by bluehead24** [gaoryrt/hexo-theme-pln#8]
就是浏览器分页栏上显示的页面图标，我把ico和png都放在了source目录下，但是似乎并没有效果。
请问该如何设置?

**Comment by gaoryrt** [comment]
（都放在网页头部）
Chrome 上使用 favicon.ico：
    `<link rel="icon" type="image/x-icon" href="/favicon.ico">`
Safari 使用 apple-touch-icon-precomposed.png：
    `<link href="/apple-touch-icon-precomposed.png" sizes="180x180" rel="apple-touch-icon-precomposed">`
貌似后面那个我并没有加到本项目的模板中，还请自己加

**Comment by gaoryrt** [comment]
参考 [https://github.com/gaoryrt/gaoryrt.github.io](https://github.com/gaoryrt/gaoryrt.github.io) 的文件格式放在根目录

**Comment by bluehead24** [comment]
解决了，多谢指教。顺便，似乎在chrome上png更好些，之前ico莫名一直不能加载，而edge和firefox都正常。

**Comment by gaoryrt** [comment]
不谢～
