### ISSUE TITLE
使用中遇到的问题

### ISSUE THREAD

**Issue by A1rChina** [gaoryrt/hexo-theme-pln#9]
- rss输出需要插件支持，这点作者可以写进README文件中提醒一下
- 不知怎么的search.xml无法生成，无法体验搜索服务
  以上，如果作者有空的话可以解答下么。thx
  ----------------------->
  谢谢 @Stephen-Chen 的解答。
  综上，建议作者可以在Readme文件中注释需要两个插件的支持

**Comment by Steven1677** [comment]
1. 需要作者自己添加，我帮助不了你。
2. see http://hahack.com/codes/local-search-engine-for-hexo/
3. 在你的 hexo 博客根目录下，有一个 _config.yml 文件，里面默认有一个 subtitle 选项，请填上内容，否则主题显示可能不正常。

_我只是一个博客主题的使用者，希望能够帮到你。_

**Comment by sbgov** [comment]
subtitle这个点我是指你说的

>  avoid bug
我遇到的问题最重要的还是无法生成xml文件

**Comment by gaoryrt** [comment]
三个问题 @Stephen-Chen  说的比较明白了
1.确实是要hexo-generator-feed插件
2.搜索插件是参考的上面链接，我没有写这个教程，也是安装插件
3.建议添加subtitle字段，不然生成出来不好看

**Comment by gaoryrt** [comment]
## tl;dr

在你的 hexo 根目录下执行 shell 语句：  

```
$ npm install --save hexo-generator-search
```

在 `_config.yml` 文件中添加配置信息：  

```
search:
  path: search.xml
  field: all
```

然后 `hexo d` 就行了
